[package]
name = "asefile"
version = "0.1.1"
authors = ["Alponso <alpine.alpaca.games@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3"
log = "0.4"
flate2 = "1.0"
bitflags = "1.2"

[dependencies.image]
version = "0.23"
default-features = false
features = ["png"]

[dev-dependencies]
rand = "0.7"
